export class Employee {
    employeeId: number;
    employeeName: string;
    employeeCode: string;
    numericCode: string;
    stringCode: string;
    gender: string;
    aadhaarNumber: string;
    dob: string;
    age: string;
    workPlace: string;
    contactNo: string;
    doj: string;
    passedOutYear: string;
    designationId: string;
    designationName: string;
    companyId: string;
    companyFName: string;
    departmentId: string;
    departmentFName: string;
    vendorId: string;
    vendorName: string;
    categoryId: string;
    stateId: string;
    cityId: string;
    cityName: string;
    degreeId: string;
    experience: string;
    loginName: string;
    loginPassword: string;
    employementType: any;
    totalExperience: any;
    requiredExperience: any;
    recordStatus:number;

    constructor() {
        this.employeeId = 0;
        this.employeeName = '';
        this.employeeCode = '';
        this.numericCode = '';
        this.stringCode = '';
        this.gender = '';
        this.aadhaarNumber = '';
        this.dob = '';
        this.age = '';
        this.workPlace = '';
        this.contactNo = '';
        this.doj = '';
        this.passedOutYear = '';
        this.designationId = '';
        this.designationName = '';
        this.companyId = '';
        this.companyFName = '';
        this.departmentId = '';
        this.departmentFName = '';
        this.vendorId = '';
        this.vendorName = '';
        this.categoryId = '';
        this.stateId = '1';
        this.cityId = '';
        this.cityName = '';
        this.degreeId = '';
        this.employementType = '';
        this.experience = '';
        this.loginName = 'qwerty';
        this.loginPassword = '12345';
        this.totalExperience = '';
        this.requiredExperience = '';
        this.recordStatus = 1;
    }
}
